#!/bin/sh
set -eu
for YO in ~/github-checkout/config-files-api/*/.yardopts; do
    DIR=${YO%/*}
    BASE=${DIR##*/}
    echo "$BASE ($DIR)"
    (
        cd $DIR
        yard doc --db /tmp/.yardoc --quiet --list
    ) | cut -d' ' -f2 | LANG=POSIX sort > $BASE.list
done
